### ISSUE TITLE
Can't build on macOS 10.14.2

### ISSUE THREAD

**Issue by Sevyls** [securesocketfunneling/ssf#69]
Hi,

I ran the following command to build:

```
$ ./generate_unix_release.sh 3.0.0 "Unix Makefiles" .. `brew --prefix boost` `brew --prefix openssl` Release ../build
```

and got the following build errors:

```
[ 10%] Building CXX object src/network/CMakeFiles/ssf_network.dir/ssf/layer/physical/tcp_helpers.cpp.o
In file included from /Users/aussmich/Projekte/ssf/src/network/ssf/layer/physical/tcp.cpp:1:
In file included from /Users/aussmich/Projekte/ssf/src/network/ssf/layer/physical/tcp.h:13:
/Users/aussmich/Projekte/ssf/src/network/ssf/layer/basic_empty_stream.h:55:24: error: 
      too many template arguments for class template 'basic_stream_socket'
  typedef boost::asio::basic_stream_socket<
                       ^
/usr/local/opt/boost/include/boost/asio/basic_stream_socket.hpp:49:7: note: 
      template is declared here
class basic_stream_socket
      ^
In file included from /Users/aussmich/Projekte/ssf/src/network/ssf/layer/physical/tcp.cpp:1:
In file included from /Users/aussmich/Projekte/ssf/src/network/ssf/layer/physical/tcp.h:13:
/Users/aussmich/Projekte/ssf/src/network/ssf/layer/basic_empty_stream.h:58:24: error: 
      too many template arguments for class template 'basic_socket_acceptor'
  typedef boost::asio::basic_socket_acceptor<
                       ^
/usr/local/opt/boost/include/boost/asio/basic_socket_acceptor.hpp:73:7: note: 
      template is declared here
class basic_socket_acceptor
      ^
In file included from /Users/aussmich/Projekte/ssf/src/network/ssf/layer/physical/tcp.cpp:1:
In file included from /Users/aussmich/Projekte/ssf/src/network/ssf/layer/physical/tcp.h:13:
/Users/aussmich/Projekte/ssf/src/network/ssf/layer/basic_empty_stream.h:228:26: error: 
      no member named 'async_result_init' in namespace 'boost::asio::detail'
    boost::asio::detail::async_result_init<ConnectHandler,
    ~~~~~~~~~~~~~~~~~~~~~^
/Users/aussmich/Projekte/ssf/src/network/ssf/layer/basic_empty_stream.h:228:44: error: 
      'ConnectHandler' does not refer to a value
    boost::asio::detail::async_result_init<ConnectHandler,
                                           ^
/Users/aussmich/Projekte/ssf/src/network/ssf/layer/basic_empty_stream.h:223:22: note: 
      declared here
  template <typename ConnectHandler>
                     ^
/Users/aussmich/Projekte/ssf/src/network/ssf/layer/basic_empty_stream.h:229:74: error: 
      expected '(' for function-style cast or type construction
                                           void(boost::system::error_code)>
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~^
/Users/aussmich/Projekte/ssf/src/network/ssf/layer/basic_empty_stream.h:240:9: error: 
      use of undeclared identifier 'init'
        init.handler)();
        ^
/Users/aussmich/Projekte/ssf/src/network/ssf/layer/basic_empty_stream.h:242:12: error: 
      use of undeclared identifier 'init'
    return init.result.get();
           ^
/Users/aussmich/Projekte/ssf/src/network/ssf/layer/basic_empty_stream.h:404:20: error: 
      too many template arguments for class template 'basic_socket'
      boost::asio::basic_socket<Protocol1, SocketService>& peer,
                   ^                       ~~~~~~~~~~~~~~
/usr/local/opt/boost/include/boost/asio/basic_socket.hpp:60:7: note: template is
      declared here
class basic_socket
      ^
In file included from /Users/aussmich/Projekte/ssf/src/network/ssf/layer/physical/tcp.cpp:1:
In file included from /Users/aussmich/Projekte/ssf/src/network/ssf/layer/physical/tcp.h:13:
/Users/aussmich/Projekte/ssf/src/network/ssf/layer/basic_empty_stream.h:433:33: error: 
      too many template arguments for class template 'basic_socket'
                   boost::asio::basic_socket<Protocol1, SocketService>& peer,
                                ^                       ~~~~~~~~~~~~~~
/usr/local/opt/boost/include/boost/asio/basic_socket.hpp:60:7: note: template is
      declared here
class basic_socket
      ^
In file included from /Users/aussmich/Projekte/ssf/src/network/ssf/layer/physical/tcp.cpp:1:
In file included from /Users/aussmich/Projekte/ssf/src/network/ssf/layer/physical/tcp.h:13:
/Users/aussmich/Projekte/ssf/src/network/ssf/layer/basic_empty_stream.h:437:26: error: 
      no member named 'async_result_init' in namespace 'boost::asio::detail'
    boost::asio::detail::async_result_init<AcceptHandler,
    ~~~~~~~~~~~~~~~~~~~~~^
/Users/aussmich/Projekte/ssf/src/network/ssf/layer/basic_empty_stream.h:437:44: error: 
      'AcceptHandler' does not refer to a value
    boost::asio::detail::async_result_init<AcceptHandler,
                                           ^
/Users/aussmich/Projekte/ssf/src/network/ssf/layer/basic_empty_stream.h:430:66: note: 
      declared here
  template <typename Protocol1, typename SocketService, typename AcceptHandler>
                                                                 ^
/Users/aussmich/Projekte/ssf/src/network/ssf/layer/basic_empty_stream.h:438:74: error: 
      expected '(' for function-style cast or type construction
                                           void(boost::system::error_code)>
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~^
/Users/aussmich/Projekte/ssf/src/network/ssf/layer/basic_empty_stream.h:449:62: error: 
      too many template arguments for class template 'basic_socket'
        typename std::remove_reference<typename boost::asio::basic_socket<
                                                             ^
/usr/local/opt/boost/include/boost/asio/basic_socket.hpp:60:7: note: template is
      declared here
class basic_socket
      ^
In file included from /Users/aussmich/Projekte/ssf/src/network/ssf/layer/physical/tcp.cpp:1:
In file included from /Users/aussmich/Projekte/ssf/src/network/ssf/layer/physical/tcp.h:13:
/Users/aussmich/Projekte/ssf/src/network/ssf/layer/basic_empty_stream.h:450:40: error: 
      expected a qualified name after 'typename'
            Protocol1, SocketService>::native_handle_type>::type,
                                       ^
/Users/aussmich/Projekte/ssf/src/network/ssf/layer/basic_empty_stream.h:455:9: error: 
      use of undeclared identifier 'init'
        init.handler)();
        ^
/Users/aussmich/Projekte/ssf/src/network/ssf/layer/basic_empty_stream.h:457:12: error: 
      use of undeclared identifier 'init'
    return init.result.get();
           ^
16 errors generated.
make[2]: *** [src/network/CMakeFiles/ssf_network.dir/ssf/layer/physical/tcp.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/network/CMakeFiles/ssf_network.dir/all] Error 2
make: *** [all] Error 2
```
